from locators.web_site_old.for_header_testing import HeaderLocators
from locators.web_site_old.for_objects_page import ObjectsPageLocators
from locators.web_site_old.for_Become_partner import BecomePartnerLocators
from locators.web_site_old.for_contacts_page import ContactsLocators
from locators.web_site_old.for_local_testing import LocalLocators
from locators.web_site_old.for_subscription_types import SubscriptionTypesLocators
from locators.web_site_old.for_footer_testing import FooterLocators
from locators.web_site_old.for_main_page_locators import MainPageLocators